[versions]
android-gradle-plugin = "9.5.0-alpha03"
kotlin = "2.4.20-RC2"

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[libraries]
rxjava = { module = "io.reactivex.rxjava2:rxjava", version = "2.2.21" }
